name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.2.0'
          projectPath: ${{github.workspace}}
          args: './katalonc -noSplash -runMode=console -projectPath="/Users/katalon/git/GitHubAction/GitHubAction.prj" -retry=0 -testSuitePath="Test Suites/TS GitHub Action/Github Action Test Suite" -executionProfile="default" -browserType="Chrome" -apiKey="ac0360a1-d23b-4b80-b61f-c5291b4cc878" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=false -kobiton.authentication.serverUrl="https://api.kobiton.com/wd/hub" -kobiton.authentication.username="coty_katalon" -kobiton.authentication.apiKey="7b100a30-69eb-4410-ba48-629281247a37" -webui.autoUpdateDrivers=true'
