name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.2.0'
          projectPath: '${{github.workspace}}'
          args: 'katalonc -noSplash -retry=0 -testSuitePath="Test Suites/TS GitHub Action/Github Action Test Suite" -executionProfile="default" -browserType="Chrome" -apiKey= ${{secrets.KATALON_API_KEY}} --config -webui.autoUpdateDrivers=true'
